### PR TITLE
Test on arm64 and ppc64

### PR DESCRIPTION
**Pull request by elijahr**
This is partially to debug https://github.com/dom96/choosenim/pull/213, but seems valuable outside of that.

Related: https://github.com/nimterop/nimterop/pull/249

### CODE REVIEW

**Comment by genotrance** [comment]
I'll recommend getting in touch on [gitter](https://gitter.im/nimterop/Lobby) or irc to discuss your changes.

**Comment by elijahr** [comment]
@genotrance The build is green. Thanks again for your help 😄

**Comment by genotrance** [comment]
I was thinking the better fix would be to post precompiled static binaries for iconv as well, like I have for libarchive on bintray. I have kicked off the process and it should be posted in some time.

As for the travis changes, it might be better to update the [gist](https://gist.github.com/genotrance/fb53504a4fba88bc5201d3783df5c522/#file-travis-sh) so that all these projects can get the benefit.

Let me know your thoughts.

**Comment by elijahr** [comment]
@genotrance That's a good plan; building iconv takes a long time. I'll have some time tonight to update the gist, but if you have time and inclination before then, feel free. Thanks!

**Pull request closed without merging**
